[build]
  command = "npx prisma generate && npm run build"
  publish = ".next"
  # Ignore warning messages during build process
  ignore_warnings = true
[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  # Configure Node.js version (updated to meet package requirements)
  NODE_VERSION = "18.18.0"
  NPM_FLAGS = "--legacy-peer-deps" 